apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: '{{ role }}'
  name: '99-{{ role }}-kargs'
spec:
  kernelArguments:
{% for option in rhcos_kernel_options %}
     - '{{ option }}'
{% endfor %}
