---
# defaults file

workdir: ~/ocp4-workdir
rhcos_pre_kernel_options: []
log_level: info
release_image_override: ""
proxy_url: ""
no_proxy: ""
enable_local_registry: false

chronyconfig:
   enabled: true

cni_network_provider: OpenshiftSDN

cluster_network_cidr: 10.128.0.0/14
cluster_network_hostprefix: 23
service_network: 172.30.0.0/16
