---

ibm_cloud_dl_endpoint_net_cidr: ""  #IBM Cloud DirectLink endpoint network cidr eg. 10.0.0.0/8
ibm_cloud_http_proxy: ""            #IBM Cloud http/squid proxy eg. http://10.166.13.64:3128
ocp_node_net_gw: ""                 #OCP node private network gateway eg. 192.168.25.1
ocp_node_net_intf: ""               #OCP node private network interface name eg. env3

