---
# tasks file for csi driver configuration

- name: Set providerID spec for OCP Nodes
  k8s:
    state: present
    kind: Node
    name: "{{ item.name }}"
    definition:
      spec:
        providerID: ibmpowervs://{{ region }}/{{ zone }}/{{ service_instance_id }}/{{ item.id }}
  with_items:
    - "{{ masters | lower }}"
    - "{{ workers | lower }}"
